version: '3.3'

services:
  server:
    container_name: justsend-api
    build: .
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_PORT: ${APP_PORT}
      EXTERNAL_URL: ${EXTERNAL_URL}
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    deploy:
      resources:
        limits:
          memory: 1024M

  db:
    container_name: justsend-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.50'

volumes:
  postgres_data:
