#!/bin/sh

staged_files=$(git diff --staged --name-only)

./gradlew ktlintFormat

echo "🧹 Running Gradle build and checks on staged files…"
./gradlew build

if [ $? -ne 0 ]; then
  echo "❌ Build or checks failed. Please fix the issues before committing."
  exit 1
fi

for file in $staged_files; do
  if test -f "$file"; then
    git add "$file"
  fi
done

echo "✅ Pre-commit check passed successfully."
